
version: '3'

networks:
  inception:

volumes:
  my_db:
    driver_opts:
     type: none
     o: bind
     device: /Users/aoustani/Desktop/db
  my_wp:
    driver_opts:
      type: none
      o: bind
      device: /Users/aoustani/Desktop/wp

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - inception
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - my_wp:/var/www/html/wordpress
    networks:
      - inception
  
  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - my_wp:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception