
# Use the official Nginx base image from Docker Hub
FROM debian:buster

# Update package lists and install Nginx
RUN apt-get update && apt-get install -y nginx openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=MA/ST=KBN/O=42-Network/CN=aoustani.42.fr" -keyout /etc/nginx/nginx.key -out /etc/nginx/nginx.crt

# Copy your custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/

# Copy your custom HTML file
COPY index.html /var/www/html/

# Expose port 443 to the host
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

